import type { FindingCategory, Severity } from "@mergeguard/core";

export interface PatternRule {
  name: string;
  re: RegExp;
  category: FindingCategory;
  severity: Severity;
  title: string;
  description: string;
  remediation: string;
  confidence: number;
  needle?: string;
  edge?: string;
}

export const pathRules: Array<[RegExp, FindingCategory, Severity, string]> = [
  [/(^|\/)(auth|oauth|jwt|session|permission|rbac|acl)(\/|\.|$)/i, "security", "high", "Security-sensitive path changed"],
  [/(migration|migrations|schema\.prisma|drizzle|\.entity\.ts$|typeorm|\.sql$)/i, "database", "high", "Database schema or migration changed"],
  [/(^|\/)(controllers?|guards?|modules?|gateways?)(\/|$)/i, "api", "medium", "NestJS application boundary changed"],
  [/(\.github\/workflows|\.gitlab-ci|Dockerfile|terraform|k8s|kubernetes|helm)/i, "scalability", "medium", "Deployment or infrastructure code changed"],
  [/(package\.json|pnpm-lock|yarn\.lock|package-lock|requirements\.txt|pyproject\.toml|go\.mod)/i, "security", "medium", "Dependency manifest changed"],
  [/(openapi|swagger|graphql|\.proto$|routes?\/|controllers?\/)/i, "api", "medium", "Public/API-facing code changed"],
];

/** Pattern detectors generate candidates only. Jev verifies ambiguous semantics. */
export const patterns: PatternRule[] = [
  { name: "dynamic-eval", re: /\beval\s*\(|new\s+Function\s*\(/, category: "security", severity: "critical", title: "Dynamic code execution introduced", description: "Dynamic evaluation can turn attacker-controlled text into executable code.", remediation: "Avoid eval/new Function. Parse or map allowed operations explicitly.", confidence: 0.94, needle: "eval", edge: "Untrusted input reaches the evaluated string." },
  { name: "shell-exec", re: /(child_process|\bexecSync\s*\(|\bexec\s*\()/, category: "security", severity: "high", title: "Shell/process execution path", description: "Process execution can become command injection when arguments are assembled from untrusted input.", remediation: "Prefer execFile/spawn with argument arrays and strict allow-list validation.", confidence: 0.78, needle: "exec", edge: "A request parameter, filename, branch name, or other untrusted string reaches the shell command." },
  { name: "innerhtml", re: /dangerouslySetInnerHTML|\.innerHTML\s*=/, category: "security", severity: "high", title: "HTML injection sink", description: "Raw HTML rendering can create XSS when the value includes untrusted content.", remediation: "Render text normally or sanitize with a well-tested HTML sanitizer before this sink.", confidence: 0.76, needle: "innerHTML", edge: "Stored or reflected user-controlled markup contains script-capable HTML." },
  { name: "weak-random", re: /Math\.random\s*\(/, category: "security", severity: "medium", title: "Non-cryptographic randomness", description: "Math.random is predictable enough that it should not generate secrets, reset tokens, OTPs, or security identifiers.", remediation: "Use crypto.randomUUID() or crypto.randomBytes() for security-sensitive values.", confidence: 0.7, needle: "Math.random", edge: "The random value is used as an authentication, invitation, reset, or authorization token." },
  { name: "jwt-decode", re: /jwt\.decode\s*\(|decodeJwt\s*\(/i, category: "security", severity: "high", title: "JWT decoded without obvious verification", description: "Decoding a JWT does not establish signature validity or trusted claims.", remediation: "Verify signature, algorithm, issuer, audience, and expiry before trusting claims.", confidence: 0.75, needle: "decode", edge: "An attacker supplies a forged token whose decoded claims are trusted." },
  { name: "open-redirect", re: /(redirect|location\.href|location\.assign)\s*\([^)]*(req\.|request\.|searchParams|query|params)/i, category: "security", severity: "medium", title: "Potential unvalidated redirect", description: "A redirect target appears influenced by request data and may permit phishing/open redirects.", remediation: "Allow-list destinations or resolve only known internal route identifiers.", confidence: 0.68, needle: "redirect", edge: "A crafted returnUrl points to an attacker-controlled origin." },
  { name: "sql-template", re: /(\$queryRawUnsafe|\$executeRawUnsafe|\.query\s*\(\s*`[^`]*\$\{|SELECT[\s\S]*\$\{)/i, category: "security", severity: "critical", title: "Potential SQL injection", description: "SQL appears to be assembled using interpolated data or an explicitly unsafe raw-query API.", remediation: "Use parameterized queries / safe tagged templates and validate dynamic identifiers separately.", confidence: 0.86, needle: "query", edge: "An attacker-controlled value changes SQL structure rather than remaining a parameter." },
  { name: "path-user-input", re: /(readFile|writeFile|createReadStream|createWriteStream|sendFile|unlink|rm)\s*\([^)]*(req\.|request\.|params|query|body)/i, category: "security", severity: "high", title: "Potential path traversal", description: "A filesystem path appears influenced by request data.", remediation: "Resolve against a fixed root and reject paths that escape it; avoid accepting raw filesystem paths from clients.", confidence: 0.72, needle: "File", edge: "Input contains ../ or an absolute path that escapes the intended directory." },
  { name: "sensitive-log", re: /console\.(log|info|debug|warn)\s*\([^)]*(password|token|secret|authorization|cookie|apiKey)/i, category: "security", severity: "high", title: "Possible sensitive data logging", description: "Credential- or token-like data may be written to logs.", remediation: "Remove the sensitive value or log only a redacted identifier.", confidence: 0.82, needle: "console.", edge: "Production logs are retained or accessible to a broader audience than application memory." },
  { name: "cors-wildcard", re: /(origin\s*:\s*["']\*["']|Access-Control-Allow-Origin["']?\s*[:,]\s*["']\*["'])/i, category: "security", severity: "medium", title: "Wildcard CORS policy", description: "A wildcard origin can expose browser-accessible resources more broadly than intended.", remediation: "Allow-list trusted origins and review credential handling.", confidence: 0.72, needle: "origin", edge: "A sensitive unauthenticated or token-bearing endpoint becomes callable from arbitrary origins." },
  { name: "tls-disabled", re: /rejectUnauthorized\s*:\s*false|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*["']?0/i, category: "security", severity: "critical", title: "TLS certificate verification disabled", description: "Disabling certificate validation enables man-in-the-middle attacks.", remediation: "Keep certificate verification enabled; configure trusted CA certificates instead.", confidence: 0.97, needle: "rejectUnauthorized" },
  { name: "hash-password-md5", re: /createHash\s*\(\s*["'](md5|sha1)["']\s*\)/i, category: "security", severity: "high", title: "Weak hash algorithm", description: "MD5/SHA-1 are not appropriate for password hashing and have collision/fast-bruteforce weaknesses.", remediation: "Use Argon2id, scrypt, or bcrypt for passwords; use a modern hash where collision resistance is required.", confidence: 0.86, needle: "createHash" },
  { name: "nplusone-await-loop", re: /for\s*\([^)]*(?:of|;)[^)]*\)[\s\S]{0,500}?await\s+[^;\n]*(find|query|select|fetch|axios|request|\.get\(|\.post\()/i, category: "performance", severity: "medium", title: "Potential sequential/N+1 I/O", description: "An I/O operation appears to be awaited once per loop iteration.", remediation: "Batch the operation, join/eager-load related data, or use bounded concurrency where safe.", confidence: 0.79, needle: "await", edge: "The loop processes hundreds or thousands of items." },
  { name: "promise-all-map", re: /Promise\.all\s*\(\s*[^)]*\.map\s*\(/i, category: "scalability", severity: "medium", title: "Potential unbounded concurrency", description: "Promise.all over a collection starts all operations at once and may exhaust connections, memory, or downstream rate limits.", remediation: "Use bounded concurrency (pool/semaphore) when collection size is not strictly capped.", confidence: 0.73, needle: "Promise.all", edge: "The input collection grows with user/data volume." },
  { name: "unbounded-findmany", re: /findMany\s*\(\s*\{?\s*\}?\s*\)/i, category: "performance", severity: "medium", title: "Potential unbounded database read", description: "A collection query has no obvious limit/pagination.", remediation: "Add take/limit/cursor pagination appropriate to the caller.", confidence: 0.76, needle: "findMany", edge: "The table grows to production scale." },
  { name: "select-star", re: /SELECT\s+\*/i, category: "performance", severity: "low", title: "Broad SELECT * query", description: "Reading every column can increase I/O and couple callers to schema growth.", remediation: "Select only fields needed by this code path, especially on hot or wide tables.", confidence: 0.62, needle: "SELECT *", edge: "Rows contain large JSON/text/blob columns or the query is hot." },
  { name: "sync-io", re: /(readFileSync|writeFileSync|readdirSync|statSync|execSync)\s*\(/, category: "performance", severity: "medium", title: "Blocking synchronous I/O", description: "Synchronous I/O blocks the Node.js event loop while the operation completes.", remediation: "Use asynchronous APIs in request/worker hot paths unless startup-only behavior is intentional.", confidence: 0.74, needle: "Sync", edge: "The operation runs while serving concurrent requests." },
  { name: "json-clone", re: /JSON\.parse\s*\(\s*JSON\.stringify\s*\(/, category: "performance", severity: "low", title: "Serialization-based deep clone", description: "JSON stringify/parse duplicates the entire object and loses non-JSON values.", remediation: "Use structuredClone or copy only the fields that need mutation.", confidence: 0.67, needle: "JSON.parse", edge: "The object is large or includes Dates/undefined/BigInt/cycles." },
  { name: "quadratic-indexof", re: /\.filter\s*\([^)]*=>[\s\S]{0,150}?\.includes\s*\(/i, category: "performance", severity: "low", title: "Possible quadratic membership scan", description: "Array membership checks inside another collection pass can become O(n²).", remediation: "Use a Set/Map for repeated membership tests on potentially large collections.", confidence: 0.61, needle: "includes", edge: "Both collections grow into the thousands." },
  { name: "sort-in-loop", re: /for\s*\([^)]*\)[\s\S]{0,350}?\.sort\s*\(/i, category: "performance", severity: "medium", title: "Sorting inside a loop", description: "Repeated sorting can multiply O(n log n) work by the outer iteration count.", remediation: "Sort once outside the loop where semantics permit.", confidence: 0.68, needle: "sort", edge: "The outer loop or sorted collection is large." },
  { name: "process-local-map", re: /(?:^|\n)\s*(?:const|let|var)\s+\w+\s*=\s*new\s+(Map|Set)\s*\(/m, category: "scalability", severity: "low", title: "Process-local mutable state", description: "Module-level in-memory state is per-process and disappears on restart.", remediation: "If state must be shared/durable, use an external store or make locality explicit.", confidence: 0.62, needle: "new Map", edge: "The service scales horizontally or is restarted/deployed." },
  { name: "unbounded-array-growth", re: /\.push\s*\([^)]*\)[\s\S]{0,120}(setInterval|on\s*\(["']data|addEventListener)/i, category: "reliability", severity: "medium", title: "Potential unbounded memory growth", description: "Values appear appended in a recurring/event-driven path without an obvious bound or eviction policy.", remediation: "Cap the collection, evict old entries, stream results, or persist externally.", confidence: 0.65, needle: "push", edge: "The process stays alive for a long time or receives sustained traffic." },
  { name: "interval-no-clear", re: /setInterval\s*\(/, category: "reliability", severity: "low", title: "Recurring timer introduced", description: "Recurring timers can leak work/resources if lifecycle cleanup is missing.", remediation: "Ensure clearInterval is called on shutdown/unmount and avoid duplicate timer registration.", confidence: 0.55, needle: "setInterval", edge: "The containing setup code runs multiple times." },
  { name: "event-listener", re: /\.on\s*\(\s*["'][^"']+["']\s*,|addEventListener\s*\(/, category: "reliability", severity: "low", title: "Event listener lifecycle candidate", description: "A new event listener can accumulate if registration repeats without corresponding cleanup.", remediation: "Verify removeListener/off/removeEventListener is guaranteed for repeated lifecycle entry.", confidence: 0.54, needle: "addEventListener", edge: "The registration function runs once per request/render/reconnect." },
  { name: "floating-promise", re: /(?:^|\n)\s*(?:fetch|axios\.|\w+Async\s*\(|\w+\.save\s*\(|\w+\.send\s*\()[^\n;]*;\s*$/m, category: "reliability", severity: "medium", title: "Potential unhandled asynchronous operation", description: "An async-looking operation is invoked without await/return/catch in the changed code.", remediation: "Await/return the promise or deliberately detach it with explicit error handling.", confidence: 0.58, needle: "fetch", edge: "The promise rejects after the surrounding request/function already completed." },
  { name: "catch-empty", re: /catch\s*\([^)]*\)\s*\{\s*\}/, category: "reliability", severity: "medium", title: "Exception silently swallowed", description: "An empty catch block hides failures and can leave state partially updated.", remediation: "Handle the expected failure explicitly or rethrow/log with safe context.", confidence: 0.82, needle: "catch" },
  { name: "catch-generic-success", re: /catch\s*\([^)]*\)\s*\{[\s\S]{0,250}?return\s+(true|\{\s*success\s*:\s*true)/i, category: "bug", severity: "high", title: "Failure path may report success", description: "A catch block appears to convert an exception into a success result.", remediation: "Return an error/failure state unless this exception is explicitly expected and fully recovered.", confidence: 0.8, needle: "catch", edge: "A downstream database/network operation throws." },
  { name: "divide-by-variable", re: /\/\s*[A-Za-z_$][\w$]*(?!\s*[+*/])/g, category: "bug", severity: "low", title: "Division edge case", description: "Division by a variable may produce Infinity/NaN when the denominator can be zero or non-finite.", remediation: "Validate the denominator when zero/non-finite values are possible at this boundary.", confidence: 0.48, needle: "/", edge: "The denominator is 0, NaN, or Infinity." },
  { name: "parseint-no-radix", re: /parseInt\s*\([^,\)]*\)/, category: "readability", severity: "info", title: "Implicit parseInt radix", description: "An explicit radix makes numeric parsing intent clearer and avoids surprising non-decimal assumptions in legacy environments.", remediation: "Use parseInt(value, 10) for decimal input or Number() where strict conversion is intended.", confidence: 0.45, needle: "parseInt" },
  { name: "truthy-number", re: /if\s*\(\s*\w*(count|length|amount|balance|price|page|limit)\w*\s*\)/i, category: "bug", severity: "low", title: "Numeric truthiness may conflate zero with absence", description: "A numeric-looking value is used as a boolean, so a valid zero value follows the false branch.", remediation: "Compare explicitly against null/undefined or the intended numeric boundary.", confidence: 0.55, needle: "if", edge: "The value is legitimately 0." },
  { name: "date-string", re: /new\s+Date\s*\(\s*[^)]*(req\.|query|params|body|input)/i, category: "bug", severity: "medium", title: "Ambiguous external date parsing", description: "Runtime date parsing of external strings can differ by format/timezone and silently produce Invalid Date.", remediation: "Validate an explicit date format and timezone before constructing/comparing dates.", confidence: 0.63, needle: "new Date", edge: "Input omits timezone, uses an invalid calendar date, or crosses DST boundaries." },
  { name: "array-first", re: /\w+\s*\[\s*0\s*\]\s*\./, category: "bug", severity: "medium", title: "Possible empty-array dereference", description: "The first element is dereferenced without an obvious length guard in the local pattern.", remediation: "Handle the empty collection case or prove non-emptiness at the type/boundary level.", confidence: 0.58, needle: "[0]", edge: "The collection is empty." },
  { name: "find-deref", re: /\.find\s*\([^)]*\)\s*(?:!|as\s+\w+)?\s*\./, category: "bug", severity: "medium", title: "Possible missing-item dereference", description: "Array.find can return undefined, yet the result appears immediately dereferenced.", remediation: "Handle the not-found case explicitly.", confidence: 0.78, needle: "find", edge: "No item matches the predicate." },
  { name: "non-null-assertion", re: /\w+!\.(?:\w+)/, category: "bug", severity: "low", title: "Non-null assertion hides runtime edge case", description: "A non-null assertion suppresses TypeScript checking but does not add runtime validation.", remediation: "Validate the value or make the invariant explicit before dereference.", confidence: 0.52, needle: "!.", edge: "The asserted value is null/undefined due to malformed input or stale state." },
  { name: "unsafe-json-parse", re: /JSON\.parse\s*\([^)]*(req\.|body|input|message|data)/i, category: "reliability", severity: "medium", title: "Untrusted JSON parse may throw", description: "JSON.parse throws synchronously for malformed input.", remediation: "Validate/catch parse failures at the trust boundary and enforce a schema afterward.", confidence: 0.66, needle: "JSON.parse", edge: "Input contains malformed or unexpectedly large JSON." },
  { name: "read-check-write", re: /(findUnique|findFirst|findOne|findOneBy|SELECT|\.get\s*\()[\s\S]{0,900}?if\s*\([\s\S]{0,400}?(update|save|write|delete|create)\s*\(/i, category: "concurrency", severity: "high", title: "Read-check-write race candidate", description: "State appears read, checked, and later mutated without an obvious atomic operation in the local changed code.", remediation: "Use a transaction, conditional atomic update, row lock, uniqueness constraint, or idempotency key as appropriate.", confidence: 0.66, needle: "if", edge: "Two requests execute this path concurrently against the same record." },
  { name: "check-then-create", re: /(findUnique|findFirst|findOne|findOneBy|exists|count)\s*\([\s\S]{0,700}?(create|save)\s*\(/i, category: "concurrency", severity: "high", title: "Check-then-create race candidate", description: "A pre-check followed by create can race unless the database enforces uniqueness and the conflict is handled.", remediation: "Enforce the invariant with a unique constraint/upsert/transaction and handle conflicts.", confidence: 0.72, needle: "create", edge: "Two requests create the same logical resource simultaneously." },
  { name: "typeorm-raw-query", re: /\.(query|queryRunner\.query)\s*\(\s*[`'"]/i, category: "security", severity: "high", title: "TypeORM raw query", description: "A raw TypeORM query can become SQL injection if values are interpolated instead of parameterized.", remediation: "Use QueryBuilder parameters or a parameterized query array.", confidence: 0.74, needle: "query", edge: "A request value is concatenated into the SQL string." },
  { name: "typeorm-interpolated-where", re: /\.where\s*\(\s*`[^`]*\$\{/i, category: "security", severity: "critical", title: "Interpolated TypeORM WHERE clause", description: "QueryBuilder.where appears to interpolate values into SQL.", remediation: "Use :param placeholders and a parameter object.", confidence: 0.9, needle: "where", edge: "An attacker-controlled value changes SQL structure." },
  { name: "typeorm-synchronize", re: /synchronize\s*:\s*true/, category: "database", severity: "high", title: "TypeORM synchronize enabled", description: "synchronize: true can alter production schema automatically.", remediation: "Disable synchronize in production and use explicit migrations.", confidence: 0.88, needle: "synchronize" },
  { name: "typeorm-unbounded-find", re: /\.find\s*\(\s*\)|\.find\s*\(\s*\{\s*\}\s*\)/, category: "performance", severity: "medium", title: "Potential unbounded TypeORM find", description: "A TypeORM find() call has no obvious where/take limit.", remediation: "Add a restrictive where clause and pagination.", confidence: 0.7, needle: "find", edge: "The table grows to production scale." },
  { name: "multi-write-no-transaction", re: /(\.create|\.update|\.delete)\s*\([\s\S]{0,800}?(\.create|\.update|\.delete)\s*\(/i, category: "database", severity: "medium", title: "Multiple writes without obvious transaction", description: "Several persistence writes appear in one changed flow without an obvious transaction boundary.", remediation: "Use a transaction when the writes must succeed/fail as one business operation.", confidence: 0.6, needle: "update", edge: "A later write fails after an earlier write commits." },
  { name: "raw-db-delete-many", re: /deleteMany\s*\(\s*\{?\s*(?:where\s*:\s*\{\s*\})?\s*\}?\s*\)/i, category: "database", severity: "critical", title: "Potential unbounded delete", description: "deleteMany appears to have no restrictive predicate.", remediation: "Require an explicit, validated where clause and add safety tests for empty filters.", confidence: 0.92, needle: "deleteMany", edge: "The code path runs in production against a populated table." },
  { name: "update-many-empty", re: /updateMany\s*\(\s*\{[\s\S]{0,300}?(where\s*:\s*\{\s*\}|data\s*:)/i, category: "database", severity: "high", title: "Potential broad database update", description: "An updateMany call may operate without a meaningful restriction.", remediation: "Require a specific predicate and test that empty filters are rejected.", confidence: 0.72, needle: "updateMany", edge: "The computed filter becomes empty or undefined." },
  { name: "offset-pagination", re: /(skip|offset)\s*:\s*[^,\n]+[\s\S]{0,180}?(take|limit)/i, category: "scalability", severity: "low", title: "Offset pagination scalability candidate", description: "Large offsets can become increasingly expensive and unstable under concurrent inserts.", remediation: "Prefer cursor/keyset pagination for large, frequently changing datasets.", confidence: 0.55, needle: "skip", edge: "Users navigate deep into a large table." },
  { name: "not-null-migration", re: /ADD\s+(?:COLUMN\s+)?[\w"`]+\s+[^;\n]+NOT\s+NULL(?![\s\S]{0,100}DEFAULT)/i, category: "database", severity: "high", title: "NOT NULL migration without obvious backfill/default", description: "Adding a required column to a populated table can fail or force a blocking rewrite depending on the database and migration strategy.", remediation: "Use a staged migration: nullable/default, backfill, validate, then enforce NOT NULL.", confidence: 0.8, needle: "NOT NULL", edge: "The table already contains rows." },
  { name: "drop-column", re: /DROP\s+(?:COLUMN|TABLE)\b/i, category: "database", severity: "high", title: "Destructive schema migration", description: "The migration removes schema objects and may cause irreversible data loss or break old application versions during rollout.", remediation: "Use an expand/contract deployment and verify backups/data migration before destructive cleanup.", confidence: 0.88, needle: "DROP", edge: "Old application instances or consumers still reference the removed schema." },
  { name: "create-index", re: /CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?!CONCURRENTLY)/i, category: "database", severity: "medium", title: "Index creation may block writes", description: "On large PostgreSQL tables, non-concurrent index creation can block writes for the duration.", remediation: "Consider CREATE INDEX CONCURRENTLY where supported and operationally appropriate.", confidence: 0.62, needle: "CREATE", edge: "The table is large and receives production writes during migration." },
  { name: "unique-migration", re: /ADD\s+(?:CONSTRAINT\s+\w+\s+)?UNIQUE|CREATE\s+UNIQUE\s+INDEX/i, category: "database", severity: "medium", title: "Uniqueness migration needs duplicate-data check", description: "Adding uniqueness can fail if historical duplicates already exist.", remediation: "Preflight/backfill duplicate rows before enforcing the constraint.", confidence: 0.72, needle: "UNIQUE", edge: "Existing production data contains duplicate values." },
  { name: "api-field-delete", re: /^-\s*["']?[A-Za-z_$][\w$-]*["']?\s*[:?]/m, category: "api", severity: "medium", title: "Potential contract field removal", description: "A field appears removed in the diff; if externally consumed this can be a breaking change.", remediation: "Confirm the field is internal or version/deprecate the contract before removal.", confidence: 0.5, needle: "-", edge: "An existing client still reads the removed field." },
  { name: "env-required", re: /process\.env\.[A-Z0-9_]+!/i, category: "reliability", severity: "medium", title: "Environment variable assumed present", description: "A non-null assertion on configuration can defer missing-config failure until runtime.", remediation: "Validate required environment variables at startup with a clear error.", confidence: 0.7, needle: "process.env", edge: "The variable is omitted in a new environment/deployment." },
  { name: "hardcoded-localhost", re: /["']https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?/i, category: "reliability", severity: "low", title: "Hard-coded local service endpoint", description: "A localhost URL in application code often breaks in containers, CI, or deployed environments.", remediation: "Move environment-specific endpoints into validated configuration.", confidence: 0.66, needle: "localhost", edge: "The code runs outside the developer machine." },
  { name: "retry-no-backoff", re: /for\s*\([^)]*\)[\s\S]{0,450}?catch[\s\S]{0,250}?(continue|retry)/i, category: "reliability", severity: "medium", title: "Retry loop without obvious backoff", description: "Immediate retries can amplify outages and trigger rate limits.", remediation: "Use bounded retries with exponential backoff, jitter, and retryable-error classification.", confidence: 0.58, needle: "catch", edge: "A downstream dependency remains unavailable for seconds/minutes." },
];
